# Generated by Django 2.0.6 on 2019-07-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180704_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='kind',
            field=models.CharField(choices=[('food_list', 'danh sách món ăn'), ('list_food_all', 'danh sách món ăn chia sẻ')], max_length=120, verbose_name='Kiểu Bài Đăng:'),
        ),
    ]
